name = "ontimecheck"
compatibility_date = "2024-01-01"

[triggers]
crons = []

[[workers_dev_var]]
name = "NEXT_PUBLIC_SUPABASE_URL"
value = ""
[[workers_dev_var]]
name = "NEXT_PUBLIC_SUPABASE_ANON_KEY"
value = ""
[[workers_dev_var]]
name = "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
value = ""
